# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-sample1',
                'doc_host': 'https://akashdpatel.github.io',
                'git_url': 'https://github.com/akashdpatel/nbdev-sample1',
                'lib_path': 'nbdev_sample1'},
  'syms': {'nbdev_sample1.core': {'nbdev_sample1.core.foo': ('core.html#foo', 'nbdev_sample1/core.py')}}}